---
driver:
  name: docker
  socket: unix:///var/run/docker.sock
  privileged: true
  use_sudo: false
  hostname: "simple"
  username: root

provisioner:
  name: ansible_push
  chef_bootstrap_url: nil
  ansible_config: "test/ansible.cfg"
  idempotency_test: false
  diff: true
  verbose: 'vv'

platforms:
  - name: manageiq-fine-4
    driver:
      run_command: /usr/sbin/init
      run_options: --tty -e 'container=docker'
      image: manageiq/manageiq:fine-4
      platform: centos
      publish_all: true
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/' /etc/ssh/sshd_config
        - systemctl enable sshd
        - /usr/bin/systemctl disable appliance-initialize evmserverd evminit evm-watchdog miqvmstat miqtop
        - rm -rf /var/www/miq/vmdb/certs/*
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro

verifier:
  name: inspec

suites:
  - name: import-export
    provisioner:
      playbook: "test/playbook.yml"
    verifier:
      inspec_tests:
        - path: test/inspec

