---
- name: Install git
  yum:
    name: git
    state: present

- name: Get latest files from GitHub
  git:
    repo: https://github.com/rhtconsulting/cfme-rhconsulting-scripts.git
    dest: /opt/cfme-rhconsulting-scripts

- name: Install files to /var/www/miq/vmdb/lib/tasks
  shell: make clean-install
  args:
    chdir: /opt/cfme-rhconsulting-scripts
    creates:
    - /usr/bin/miqexport
    - /usr/bin/miqimport
    - /usr/bin/export-miqdomain
    - /usr/bin/import-miqdomain

